### ISSUE TITLE
gdb挂载跑下来出现twtimer.c段错误

### ISSUE THREAD

**Issue by alphadevgo** [ireader/sdk#29]
[09:27:09]Thread 40 received signal SIGSEGV, Segmentation fault.
[09:27:09][Switching to Thread 0xaa3824b0 (LWP 29466)]
[09:27:09]0xb5c3c880 in twtimer_cascade (tm=0x1886240, tv=0x1886658, index=11)
[09:27:09]    at ../source/twtimer.c:155
[09:27:09]155     ../source/twtimer.c: No such file or directory.
[09:27:09](gdb) 
[09:27:09](gdb) 
[09:27:09](gdb) 
[09:27:09](gdb) 
[09:29:54](gdb) bt
[09:29:54]#0  0xb5c3c880 in twtimer_cascade (tm=0x1886240, tv=0x1886658, index=11)
[09:29:54]    at ../source/twtimer.c:155
[09:29:54]#1  0xb5c3c5d4 in twtimer_process (tm=0x1886240, clock=222451756)
[09:29:54]    at ../source/twtimer.c:107
[09:29:54]#2  0xb5c3c1f4 in aio_timeout_process () at src/aio-timeout.c:28
[09:29:54]#3  0xb5c37e1c in aio_worker (param=0x0) at src/aio-worker.c:23
[09:29:54]#4  0xb4ed8f6c in start_thread () from /lib/libpthread.so.0
[09:29:54]#5  0xb4d40134 in clone () from /lib/libc.so.0
[09:29:54]Backtrace stopped: previous frame identical to this frame (corrupt stack?)

**Comment by ireader** [comment]
跑的哪个测试case？

**Comment by alphadevgo** [comment]
@ireader 结合rtsp-server-test.cpp自封装实现rtsp server；send的话也封装调用aio_transport_send发送
